# Generated by Django 4.2.2 on 2023-07-06 16:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=150)),
                ('account_alias', models.CharField(max_length=150)),
                ('account_type', models.CharField(max_length=150)),
                ('account_no', models.CharField(max_length=150)),
                ('sort_code', models.CharField(max_length=150)),
                ('account_owner', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=15)),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-bank'],
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('web', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('responsible', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Add the company logo')),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_alias', models.CharField(max_length=150)),
                ('start_date', models.DateField(default=None, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('rate_type', models.CharField(max_length=150)),
                ('rate_amount', models.FloatField()),
                ('currency', models.CharField(max_length=150)),
                ('billing_period', models.CharField(max_length=15)),
                ('description', ckeditor.fields.RichTextField()),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.customers')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
