# Generated by Django 4.2.2 on 2023-07-19 22:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=150)),
                ('account_alias', models.CharField(max_length=150, unique=True)),
                ('account_type', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=150)),
                ('sort_code', models.CharField(max_length=150)),
                ('account_owner', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=15, verbose_name='currency')),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-bank'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_alias', models.CharField(max_length=150, unique=True)),
                ('start_date', models.DateField(help_text='contract start date')),
                ('end_date', models.DateField(blank=True, help_text='contract end date', null=True)),
                ('rate_type', models.CharField(max_length=150)),
                ('rate_amount', models.FloatField()),
                ('currency', models.CharField(max_length=150)),
                ('billing_period', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractSalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_ids', models.CharField(max_length=100, verbose_name='sales_ids')),
                ('invoice_number', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='invoice date')),
                ('due_date', models.DateField(default=datetime.datetime(2023, 7, 26, 22, 33, 37, 830389, tzinfo=datetime.timezone.utc), help_text='invoice due date')),
                ('is_paid_off', models.BooleanField(default=False)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/%Y-%b', verbose_name='Add an invoice file')),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('web', models.URLField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('responsible', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Add the company logo')),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text='milestone due date')),
                ('delivery_date', models.DateField(help_text='date of delivery')),
                ('milestone_number', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('milestone_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('contract', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractSalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='invoice date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.contractsalesinvoice', unique=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContractSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='date')),
                ('worked_hours', models.FloatField()),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('is_invoiced', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.contract')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.customer'),
        ),
    ]
