# Generated by Django 4.2.2 on 2023-07-11 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=150)),
                ('account_alias', models.CharField(max_length=150, unique=True)),
                ('account_type', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=150)),
                ('sort_code', models.CharField(max_length=150)),
                ('account_owner', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=15, verbose_name='currency')),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-bank'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_alias', models.CharField(max_length=150, unique=True)),
                ('start_date', models.DateField(help_text='contract start date')),
                ('end_date', models.DateField(blank=True, help_text='contract end date', null=True)),
                ('rate_type', models.CharField(max_length=150)),
                ('rate_amount', models.FloatField()),
                ('currency', models.CharField(max_length=150)),
                ('billing_period', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('web', models.URLField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('responsible', models.CharField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Add the company logo')),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='date')),
                ('worked_hours', models.FloatField(default=8)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('contract', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.contract')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.customer'),
        ),
    ]
