# Generated by Django 4.2.2 on 2023-07-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='due_date',
            field=models.DateTimeField(help_text='contract_due_date', null=True),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='start_date',
            field=models.DateTimeField(help_text='contract_start_date'),
        ),
    ]
