# Generated by Django 4.2.2 on 2023-07-12 00:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractWithMileStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_alias', models.CharField(max_length=150, unique=True)),
                ('start_date', models.DateField(help_text='contract start date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('milestone_count', models.IntegerField()),
                ('currency', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 12, 0, 27, 17, 797486, tzinfo=datetime.timezone.utc), help_text='date'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='worked_hours',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text='milestone due date')),
                ('delivery_date', models.DateField(help_text='date of delivery')),
                ('milestone_number', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('milestone_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('contract', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.contractwithmilestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
