# Generated by Django 4.2.2 on 2023-07-20 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_contractsalesinvoice_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsalesinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total_amount'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 8, 13, 50, 522595, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
