# Generated by Django 4.2.2 on 2023-07-04 14:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_customers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
