# Generated by Django 4.2.2 on 2023-07-12 00:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_contractwithmilestone_alter_contractsale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 12, 0, 35, 10, 646589, tzinfo=datetime.timezone.utc), help_text='date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='contract',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.contract'),
        ),
        migrations.DeleteModel(
            name='ContractWithMileStone',
        ),
    ]
