# Generated by Django 4.2.2 on 2023-07-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_contracts_due_date_alter_contracts_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='due_date',
        ),
        migrations.AddField(
            model_name='contracts',
            name='end_date',
            field=models.DateField(help_text='contract due date', null=True),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='start_date',
            field=models.DateField(help_text='contract start date'),
        ),
    ]
