# Generated by Django 4.2.2 on 2023-07-20 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_contractsalesinvoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsale',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 20, 24, 59, 780319, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
