# Generated by Django 4.2.2 on 2023-07-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_customers_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add the company logo'),
        ),
    ]
