# Generated by Django 4.2.2 on 2023-07-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_contracts_description_alter_contracts_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='note',
        ),
        migrations.AddField(
            model_name='contracts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='end_date',
            field=models.DateField(blank=True, help_text='contract end date', null=True),
        ),
    ]
