# Generated by Django 4.2.2 on 2023-07-15 20:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_contractsale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 20, 45, 50, 564786, tzinfo=datetime.timezone.utc), help_text='date'),
        ),
        migrations.CreateModel(
            name='ContractSalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('date', models.DateField(help_text='invoice date')),
                ('due_date', models.DateField(help_text='invoice due date')),
                ('note', models.TextField(blank=True)),
                ('sales', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.contractsale')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
