# Generated by Django 4.2.2 on 2023-07-21 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_contractsale_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='description',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 28, 18, 20, 38, 53881, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 4, 18, 20, 38, 52868, tzinfo=datetime.timezone.utc), help_text='date of delivery'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 28, 18, 20, 38, 52868, tzinfo=datetime.timezone.utc), help_text='milestone due date'),
        ),
    ]
