# Generated by Django 4.2.2 on 2023-07-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_contracts_note_contracts_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
