# Generated by Django 4.2.2 on 2023-07-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_bankaccounts_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
