# Generated by Django 4.2.2 on 2023-07-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_customers_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='account_type',
            field=models.CharField(max_length=50),
        ),
    ]
