# Generated by Django 4.2.2 on 2023-07-22 00:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_ratetype_alter_contractsalesinvoice_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='billing_period',
        ),
        migrations.AlterField(
            model_name='contract',
            name='rate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.ratetype'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 0, 1, 36, 567937, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 5, 0, 1, 36, 566939, tzinfo=datetime.timezone.utc), help_text='date of delivery'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 0, 1, 36, 566939, tzinfo=datetime.timezone.utc), help_text='milestone due date'),
        ),
    ]
