# Generated by Django 4.2.2 on 2023-07-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_bankaccounts_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=150)),
                ('account_alias', models.CharField(max_length=150)),
                ('account_type', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=150)),
                ('sort_code', models.CharField(max_length=150)),
                ('account_owner', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=15, verbose_name='currency')),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-bank'],
            },
        ),
        migrations.RenameModel(
            old_name='Contracts',
            new_name='Contract',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.DeleteModel(
            name='BankAccounts',
        ),
    ]
