# Generated by Django 4.2.2 on 2023-07-15 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_contractsale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 21, 3, 44, 382967, tzinfo=datetime.timezone.utc), help_text='date'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 21, 3, 44, 382967, tzinfo=datetime.timezone.utc), help_text='invoice date'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 22, 21, 3, 44, 382967, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
