# Generated by Django 4.2.2 on 2023-07-22 00:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_contract_billing_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(max_length=100, verbose_name='Billing period')),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 0, 22, 59, 573402, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 5, 0, 22, 59, 573402, tzinfo=datetime.timezone.utc), help_text='date of delivery'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 0, 22, 59, 573402, tzinfo=datetime.timezone.utc), help_text='milestone due date'),
        ),
        migrations.AlterField(
            model_name='ratetype',
            name='rate_type',
            field=models.CharField(max_length=100, verbose_name='rate type'),
        ),
        migrations.AlterField(
            model_name='ratetype',
            name='billing_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.billingperiod'),
        ),
    ]
