# Generated by Django 4.2.2 on 2023-07-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_contractsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractsale',
            name='contracts',
        ),
        migrations.AddField(
            model_name='contractsale',
            name='contract_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.contract'),
        ),
    ]
