# Generated by Django 4.2.2 on 2023-07-22 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_contractsalesinvoice_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 19, 18, 54, 865596, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='contract_type',
            field=models.CharField(max_length=100, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 5, 19, 18, 54, 865596, tzinfo=datetime.timezone.utc), help_text='date of delivery'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 19, 18, 54, 865596, tzinfo=datetime.timezone.utc), help_text='milestone due date'),
        ),
        migrations.AlterField(
            model_name='ratetype',
            name='rate_type',
            field=models.CharField(max_length=100, verbose_name='Rate Type'),
        ),
    ]
