# Generated by Django 4.2.2 on 2023-07-22 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_contractsalesinvoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='field_attributes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 20, 1, 14, 872574, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 5, 20, 1, 14, 872574, tzinfo=datetime.timezone.utc), help_text='date of delivery'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 20, 1, 14, 872574, tzinfo=datetime.timezone.utc), help_text='milestone due date'),
        ),
    ]
