# Generated by Django 4.2.2 on 2023-07-23 00:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_remove_contractsale_worked_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsalesinvoice',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.contract'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 0, 43, 34, 913746, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 0, 43, 34, 913746, tzinfo=datetime.timezone.utc), help_text='date of delivery'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 0, 43, 34, 913746, tzinfo=datetime.timezone.utc), help_text='milestone due date'),
        ),
    ]
