# Generated by Django 4.2.2 on 2023-07-23 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_contractsalesinvoice_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractsalesinvoice',
            name='contract',
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 0, 44, 6, 298834, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 0, 44, 6, 298834, tzinfo=datetime.timezone.utc), help_text='date of delivery'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 0, 44, 6, 298834, tzinfo=datetime.timezone.utc), help_text='milestone due date'),
        ),
    ]
