# Generated by Django 4.2.2 on 2023-07-16 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_alter_contractsale_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsalesinvoice',
            name='is_paid_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 9, 32, 42, 750133, tzinfo=datetime.timezone.utc), help_text='date'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 9, 32, 42, 750133, tzinfo=datetime.timezone.utc), help_text='invoice date'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 23, 9, 32, 42, 750133, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
