# Generated by Django 4.2.2 on 2023-07-16 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_contractsalesinvoice_is_paid_off_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 9, 34, 28, 819791, tzinfo=datetime.timezone.utc), help_text='date'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 9, 34, 28, 819791, tzinfo=datetime.timezone.utc), help_text='invoice date'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 23, 9, 34, 28, 819791, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
