# Generated by Django 4.2.2 on 2023-07-16 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_contractsale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 23, 9, 40, 22, 116861, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
