# Generated by Django 4.2.2 on 2023-07-16 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_alter_contractsalesinvoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 23, 22, 10, 25, 916620, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.CreateModel(
            name='ContractSalesTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='invoice date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.bankaccount')),
                ('invoice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.contractsalesinvoice')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
