# Generated by Django 4.2.2 on 2023-07-17 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_contractsalesinvoice_due_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractSalesTransactions',
            new_name='ContractSalesTransaction',
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 10, 25, 12, 219839, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
