# Generated by Django 4.2.2 on 2023-07-17 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_rename_contractsalestransactions_contractsalestransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 18, 6, 0, 332076, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
