# Generated by Django 4.2.2 on 2023-07-17 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_alter_contractsalesinvoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.customer'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.contract'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 18, 21, 55, 929545, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.contractsale'),
        ),
        migrations.AlterField(
            model_name='contractsalestransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount'),
        ),
    ]
