# Generated by Django 4.2.2 on 2023-07-17 20:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_alter_contract_customer_alter_contractsale_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 24, 20, 57, 3, 951648, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.contractsale', unique=True),
        ),
        migrations.AlterField(
            model_name='contractsalestransaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.contractsalesinvoice', unique=True),
        ),
    ]
