# Generated by Django 4.2.2 on 2023-07-18 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_alter_contractsalesinvoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsalesinvoice',
            name='invoice_file',
            field=models.ImageField(blank=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 13, 37, 57, 898451, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
