# Generated by Django 4.2.2 on 2023-07-18 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_contractsalesinvoice_invoice_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 13, 41, 28, 223031, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
