# Generated by Django 4.2.2 on 2023-07-18 14:34

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_alter_contractsalesinvoice_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 14, 34, 55, 528854, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='invoice_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/invoices'), upload_to=''),
        ),
    ]
