# Generated by Django 4.2.2 on 2023-07-18 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_alter_contractsalesinvoice_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 16, 12, 46, 555598, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
