# Generated by Django 4.2.2 on 2023-07-18 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_alter_contractsalesinvoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 16, 58, 31, 567320, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Add an invoice file'),
        ),
    ]
