# Generated by Django 4.2.2 on 2023-07-18 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_contractsale_is_invoiced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 17, 26, 26, 35871, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
    ]
