# Generated by Django 4.2.2 on 2023-07-18 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_alter_contractsalesinvoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 20, 57, 46, 997303, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Add the company logo'),
        ),
    ]
