# Generated by Django 4.2.2 on 2023-07-18 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0052_alter_contractsalesinvoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 23, 38, 17, 781912, tzinfo=datetime.timezone.utc), help_text='invoice due date'),
        ),
        migrations.AlterField(
            model_name='contractsalesinvoice',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y-%b', verbose_name='Add an invoice file'),
        ),
    ]
